name: ilib_locale
description: Dart port of ilib-locale - BCP-47 locale specifier (language, region, script, variant).
version: 0.1.0
repository: https://github.com/ilib-js/ilib-locale
license: Apache-2.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ilib_env:
    path: ../../ilib-env/dart

dev_dependencies:
  test: ^1.24.0
